### ISSUE TITLE
DB dump in repository

### ISSUE THREAD

**Issue by micschk** [tractorcow/silverstripe-twitter#8]
There's a database dump included in this repo?

**Comment by tractorcow** [comment]
Oh no, there was a "no lines shown" file in https://github.com/tractorcow/silverstripe-twitter/pull/7/files

**Comment by tractorcow** [comment]
Fixed with https://github.com/tractorcow/silverstripe-twitter/commit/09a201181c85c3063fef932b0150ce4d7aed2661

@simonwinter you need to get back to me if this contained any sensitive data; I might need to do some major squashing to hide this if that's the case. :D Hopefully it's only test data.

**Comment by simonwinter** [comment]
@tractorcow ah yeah, my bad. It's nothing sensitive - sorry, a default hook was dumping the current project's db :D All good.

**Comment by tractorcow** [comment]
:D

**Comment by tractorcow** [comment]
I just noticed there was no stable release. I've tagged https://github.com/tractorcow/silverstripe-twitter/releases/tag/3.1.0
